# Generated by Django 4.2 on 2023-04-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_remove_product_categories_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
