# Generated by Django 4.2 on 2023-04-06 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_remove_review_categories_delete_rating_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(blank=True, max_length=20, null=True)),
                ('overall', models.FloatField(blank=True, null=True)),
                ('verified', models.BooleanField(blank=True, null=True)),
                ('reviewTime', models.CharField(blank=True, max_length=50, null=True)),
                ('reviewerID', models.CharField(blank=True, max_length=20, null=True)),
                ('reviewerName', models.CharField(blank=True, max_length=50, null=True)),
                ('reviewText', models.TextField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, max_length=100, null=True)),
                ('unixReviewTime', models.IntegerField(blank=True, null=True)),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('vote', models.IntegerField(blank=True, null=True)),
                ('style', models.JSONField(blank=True, null=True)),
                ('categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.category')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.review')),
            ],
        ),
    ]
