# Generated by Django 4.2 on 2023-04-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='asin',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Product'),
        ),
    ]
