# Generated by Django 4.2 on 2023-04-06 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_alter_review_asin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='asin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.product'),
        ),
    ]
