# Generated by Django 4.2 on 2023-04-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_alter_review_asin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='asin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
