# Generated by Django 4.2 on 2023-04-06 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_remove_review_asin'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='asin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.product'),
        ),
    ]
