# Generated by Django 4.2 on 2023-04-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_review_asin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
