# Generated by Django 4.2 on 2023-04-07 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_alter_product_categories_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='asin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.product'),
        ),
    ]
