# Generated by Django 4.2 on 2023-04-07 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_rename_categories_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='categories',
            new_name='category',
        ),
    ]
