# Generated by Django 4.2 on 2023-04-07 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_category_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='keywords',
        ),
    ]
