# Generated by Django 4.2 on 2023-04-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_remove_category_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
