# Generated by Django 4.2 on 2023-04-07 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0028_setup_remove_keyword_category_keyword_key_adj_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='overall',
            new_name='ratings',
        ),
    ]
